import van from "vanjs-core";
import { Deferred } from "@/shared/lib/deferred";
import { fetcher } from "@/shared/lib/fetcher";

/** Static subset of the REST Countries dataset, generated by `scripts/build-countries.mjs` */
const COUNTRIES_URL = "/countries.json";

/** Globe geojson ids (Natural Earth adm0_a3) which differ from ISO alpha-3 */
const ISO_A3_BY_COUNTRY_ID: Partial<Record<string, string>> = {
	KOS: "UNK",
	SAH: "ESH",
	PSX: "PSE",
};

const deferredCountries = new Deferred(
	() => fetcher(COUNTRIES_URL) as Promise<Partial<Record<string, RestCountryData>>>
);

export async function fetchCountryData(countryId: string): Promise<RestCountryData> {
	const countries = await deferredCountries.getAsync();
	const country = countries[ISO_A3_BY_COUNTRY_ID[countryId] ?? countryId];
	if (!country) throw new Error(`No data for ${countryId}`);
	return country;
}

/** Reactive states filled once the country data is loaded (both `null` while loading) */
export const countryDataState = (countryId: string) => {
	const data = van.state<RestCountryData | null>(null);
	const error = van.state<Error | null>(null);

	fetchCountryData(countryId)
		.then((country) => {
			data.val = country;
		})
		.catch((err: Error) => {
			console.error(err);
			error.val = err;
		});

	return { data, error };
};

export type RestCountryData = {
	name: {
		common: string;
		official: string;
	};
	flag: string;
	flags: {
		png: string;
		svg: string;
		alt: string;
	};
	capital: string[];
	capitalInfo: {
		latlng: number[];
	};
	area: number;
	population: number;
	region: string;
	subregion?: string;
	tld: string[];
	currencies: {
		[key: string]: {
			name: string;
			symbol?: string;
		};
	};
	maps: {
		googleMaps: string;
		openStreetMaps: string;
	};
};
