import { useEffect, useState } from "react";
import { Deferred } from "../../shared/lib/deferred";
import { fetcher } from "../../shared/lib/fetcher";

/** Static subset of the REST Countries dataset, generated by `scripts/build-countries.mjs` */
const COUNTRIES_URL = "/countries.json";

/** Globe geojson ids (Natural Earth adm0_a3) which differ from ISO alpha-3 */
const ISO_A3_BY_COUNTRY_ID: Partial<Record<string, string>> = {
	KOS: "UNK",
	SAH: "ESH",
	PSX: "PSE",
};

const deferredCountries = new Deferred(
	() => fetcher(COUNTRIES_URL) as Promise<Partial<Record<string, RestCountryData>>>
);

export const useCountryDataFetch = (countryId: string) => {
	const [data, setData] = useState<RestCountryData | null>(null);
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState<Error | null>(null);

	useEffect(() => {
		let active = true;

		setLoading(true);
		setError(null);
		setData(null);

		deferredCountries
			.getAsync()
			.then((countries) => {
				if (!active) return;
				const country = countries[ISO_A3_BY_COUNTRY_ID[countryId] ?? countryId];
				if (country) setData(country);
				else setError(new Error(`No data for ${countryId}`));
			})
			.catch((err) => {
				console.error(err);
				if (active) setError(err);
			})
			.finally(() => {
				if (active) setLoading(false);
			});

		return () => {
			active = false;
		};
	}, [countryId]);

	return { data, loading, error };
};

export type RestCountryData = {
	name: {
		common: string;
		official: string;
	};
	flag: string;
	flags: {
		png: string;
		svg: string;
		alt: string;
	};
	capital: string[];
	capitalInfo: {
		latlng: number[];
	};
	area: number;
	population: number;
	region: string;
	subregion?: string;
	tld: string[];
	currencies: {
		[key: string]: {
			name: string;
			symbol: string;
		};
	};
	maps: {
		googleMaps: string;
		openStreetMaps: string;
	};
};
